
import "./globals.css";
import { Space_Grotesk,Geist,Medula_One } from "next/font/google"
import Script from "next/script";
const datatype = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-datatype",
});
const medulaOne = Medula_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-medula-one",
});
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});
export const metadata = {
  title: "Aman Singh | Creative Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased `}
    >
      <body className={`min-h-full flex flex-col ${datatype.variable} ${geist.variable} ${medulaOne.variable} `}>
        

        {children}
        <Script
          src="https://cdn.lordicon.com/lordicon.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
